"""
Signal Lab — IC-based cross-sectional signal evaluation (Grinold & Kahn).

Philosophy (from Active Portfolio Management):
  Evaluate signals BEFORE backtesting. A signal is the cross-sectional
  information coefficient (IC) — the rank correlation between today's signal
  values and forward returns across the universe. A signal with mean IC
  consistently > 0.02 and IC t-stat > 2 is worth a backtest; anything else
  is noise and should be discarded before any portfolio construction.

Pipeline per signal:
  1. Compute the signal panel (date × ticker), point-in-time (only data ≤ t).
  2. At each month-end, Spearman-rank-correlate signal vs. forward returns
     at multiple horizons (21 / 63 / 126 trading days).
  3. Report mean IC, IC volatility, IC t-stat (overlap-corrected for
     horizons > 1 month), hit rate, and the IC decay profile.
  4. Quintile spread (Q5 − Q1, equal-weighted) as a sanity check that the
     IC translates into a monotonic return pattern.

Signals implemented:
  momentum_12_1      — 12-month return skipping the most recent month
                       (Asness et al. 2013 convention; skip avoids reversal)
  reversal_1m        — negative 1-month return (short-term reversal)
  low_vol            — negative 252-day realized volatility (BAB / Blitz-van Vliet)
  erl_stability      — NOVEL: per-stock BOCPD expected run length (regime age).
                       Hypothesis: stocks in old, stable regimes behave
                       differently from stocks whose return distribution
                       just broke.
  regime_mom         — NOVEL: momentum × regime stability. Momentum is only
                       trusted for stocks whose regime survived the formation
                       period; a fresh change point means the 12-month return
                       was generated by a dead regime (momentum-crash logic
                       from Daniel & Moskowitz applied at the stock level).
"""
import logging
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

logger = logging.getLogger(__name__)

_ANN = 252


# ---------------------------------------------------------------------------
# Signal construction (all point-in-time: row t uses data up to and incl. t)
# ---------------------------------------------------------------------------

def momentum_12_1(prices: pd.DataFrame) -> pd.DataFrame:
    """12-month return skipping the most recent month: P[t-21] / P[t-252] − 1."""
    return prices.shift(21) / prices.shift(252) - 1.0


def reversal_1m(prices: pd.DataFrame) -> pd.DataFrame:
    """Negative trailing 1-month return — recent losers score high."""
    return -(prices / prices.shift(21) - 1.0)


def low_vol(prices: pd.DataFrame) -> pd.DataFrame:
    """Negative 252-day realized vol — low-vol stocks score high."""
    rets = prices.pct_change()
    return -rets.rolling(252, min_periods=200).std() * np.sqrt(_ANN)


def erl_panel(prices: pd.DataFrame, hazard: float = 1 / 126) -> pd.DataFrame:
    """
    Per-stock BOCPD expected run length (regime age in days).

    Run BOCPD independently on each stock's daily return series.
    Hazard 1/126 (~2 regime changes/year) — individual stocks switch
    regimes more often than the index, so a higher hazard than the
    1/252 used for SPY keeps the run-length posterior responsive.
    """
    from src.regime_models import precompute_bocpd

    rets = prices.pct_change()
    out = pd.DataFrame(index=prices.index, columns=prices.columns, dtype=float)
    for col in prices.columns:
        r = rets[col].dropna()
        if len(r) < 60:
            continue
        _, erl = precompute_bocpd(r.values, hazard=hazard)
        out.loc[r.index, col] = erl
    return out


def regime_stability(erl: pd.DataFrame, mature_days: float = 126.0) -> pd.DataFrame:
    """Map ERL to a [0, 1] stability score: 0 = regime just broke, 1 = mature."""
    return (erl / mature_days).clip(0.0, 1.0)


def regime_mom(mom: pd.DataFrame, stability: pd.DataFrame) -> pd.DataFrame:
    """
    Regime-gated momentum: trust the 12-1 momentum signal only in proportion
    to how long the stock's current return regime has survived.

    Cross-sectionally rank momentum first so the gate scales an ordering,
    not raw returns (keeps the interaction comparable across dates).
    """
    mom_rank = mom.rank(axis=1, pct=True) - 0.5   # centred cross-sectional rank
    return mom_rank * stability


# ---------------------------------------------------------------------------
# IC evaluation
# ---------------------------------------------------------------------------

def forward_returns(prices: pd.DataFrame, horizon: int) -> pd.DataFrame:
    """Forward total return over the next `horizon` trading days."""
    return prices.shift(-horizon) / prices - 1.0


def monthly_ic(
    signal: pd.DataFrame,
    prices: pd.DataFrame,
    horizons: Tuple[int, ...] = (21, 63, 126),
    min_names: int = 30,
) -> Dict[int, pd.Series]:
    """
    Spearman rank IC at each month-end, per horizon.

    Returns {horizon: Series of ICs indexed by month-end date}.
    """
    month_ends = signal.resample("ME").last().index
    # map each month-end to the last available trading day
    trade_dates = []
    for me in month_ends:
        idx = signal.index[signal.index <= me]
        if len(idx):
            trade_dates.append(idx[-1])
    trade_dates = pd.DatetimeIndex(sorted(set(trade_dates)))

    out: Dict[int, pd.Series] = {}
    for h in horizons:
        fwd = forward_returns(prices, h)
        ics, dates = [], []
        for t in trade_dates:
            if t not in signal.index or t not in fwd.index:
                continue
            s = signal.loc[t]
            f = fwd.loc[t]
            mask = s.notna() & f.notna()
            if mask.sum() < min_names:
                continue
            ic, _ = spearmanr(s[mask], f[mask])
            if np.isfinite(ic):
                ics.append(float(ic))
                dates.append(t)
        out[h] = pd.Series(ics, index=dates, name=f"IC_{h}d")
    return out


def ic_summary(ic_series: pd.Series, horizon_days: int) -> Dict[str, float]:
    """
    Mean IC, IC vol, t-stat, hit rate.

    For horizons > 21 days the monthly IC observations overlap, which
    inflates the naive t-stat. Correct by shrinking the effective sample
    size by the overlap factor (h / 21) — conservative Newey-West-style fix.
    """
    n = len(ic_series)
    if n < 12:
        return {"mean_ic": np.nan, "ic_vol": np.nan, "t_stat": np.nan,
                "hit_rate": np.nan, "n_obs": n}
    overlap = max(1.0, horizon_days / 21.0)
    n_eff = n / overlap
    mean_ic = float(ic_series.mean())
    ic_vol = float(ic_series.std())
    t_stat = mean_ic / (ic_vol + 1e-12) * np.sqrt(n_eff)
    return {
        "mean_ic": mean_ic,
        "ic_vol": ic_vol,
        "t_stat": float(t_stat),
        "hit_rate": float((ic_series > 0).mean()),
        "n_obs": n,
    }


def quintile_spread(
    signal: pd.DataFrame,
    prices: pd.DataFrame,
    horizon: int = 21,
    min_names: int = 30,
) -> Dict[str, float]:
    """
    Equal-weighted Q5 − Q1 monthly long-short return (no costs).

    Sanity check that the IC corresponds to a monotonic return pattern,
    plus the annualized spread and its Sharpe.
    """
    fwd = forward_returns(prices, horizon)
    month_ends = signal.resample("ME").last().index
    spreads, q_means = [], []
    for me in month_ends:
        idx = signal.index[signal.index <= me]
        if not len(idx):
            continue
        t = idx[-1]
        s, f = signal.loc[t], fwd.loc[t]
        mask = s.notna() & f.notna()
        if mask.sum() < min_names:
            continue
        s_v, f_v = s[mask], f[mask]
        q = pd.qcut(s_v.rank(method="first"), 5, labels=False)
        means = f_v.groupby(q).mean()
        if len(means) == 5:
            spreads.append(float(means[4] - means[0]))
            q_means.append(means.values)
    if len(spreads) < 12:
        return {"ann_spread": np.nan, "spread_sharpe": np.nan, "monotonic": np.nan}
    spreads = np.array(spreads)
    periods_per_year = _ANN / horizon
    q_avg = np.mean(np.stack(q_means), axis=0)
    mono = float(np.all(np.diff(q_avg) > 0))   # strictly increasing Q1→Q5
    return {
        "ann_spread": float(spreads.mean() * periods_per_year),
        "spread_sharpe": float(spreads.mean() / (spreads.std() + 1e-12)
                               * np.sqrt(periods_per_year / max(1.0, horizon / 21.0))),
        "monotonic": mono,
    }


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

def evaluate_signals(
    prices: pd.DataFrame,
    signals: Dict[str, pd.DataFrame],
    horizons: Tuple[int, ...] = (21, 63, 126),
) -> pd.DataFrame:
    """
    Full IC report for a dict of signal panels.

    Returns a tidy DataFrame: one row per (signal, horizon) with IC stats
    and the 1-month quintile spread attached to the 21d rows.
    """
    rows: List[dict] = []
    for name, sig in signals.items():
        ics = monthly_ic(sig, prices, horizons=horizons)
        qs = quintile_spread(sig, prices, horizon=21)
        for h in horizons:
            stats = ic_summary(ics[h], h)
            row = {"signal": name, "horizon_d": h, **stats}
            if h == 21:
                row.update(qs)
            rows.append(row)
    return pd.DataFrame(rows)
